fix submodule issue

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,10 @@ concurrency:
 
 env:
   FORCE_COLOR: "1"
-  CHECKSUM_FILE: "river-status-${{ github.ref_name }}.tar.gz.sha256"
+  TAR_FILE: "river-status-${{ github.ref_name }}.tgz"
+  TAR_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.tgz.sha256"
+  ZIP_FILE: "river-status-${{ github.ref_name }}.zip"
+  ZIP_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.zip.sha256"
 
 # inputs:
 #   github_token:
@@ -27,6 +30,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: main
+          submodules: true
 
       # Install Rust toolchain
       - name: Install Rust
@@ -54,30 +58,40 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: main
+          submodules: true
 
       - name: Set env
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
-      - name: Release
-        uses: softprops/action-gh-release@v2
-        env:
-          GITHUB_TOKEN: ${{ inputs.github-token }}
+      - name: Git-archive-all
+        uses: qmonnet/git-archive-all-action@v1.0.1
         with:
-          tag_name: ${{ env.RELEASE_VERSION }}
-          name: Release ${{ github.ref }}
-          draft: false
-          prerelease: false
+          force-submodules: true
+          output-files: ${TAR_FILE} ${ZIP_FILE}
 
-      - name: Get tarball sha256
-        env:
-          GH_TOKEN: ${{ github.token }}
-        working-directory: ${{ github.workspace }}
+      # - name: Release
+      #   uses: softprops/action-gh-release@v2
+      #   env:
+      #     GITHUB_TOKEN: ${{ inputs.github-token }}
+      #   with:
+      #     tag_name: ${{ env.RELEASE_VERSION }}
+      #     name: Release ${{ github.ref }}
+      #     draft: false
+      #     prerelease: false
+
+      - name: generate tar.gz checksums
         run: |
-          gh release download ${{ github.ref_name }} --archive=tar.gz --output ${{ github.ref_name }}.tgz
-          CONTENT=$( sha256sum ${{ github.ref_name }}.tgz )
+          # gh release download ${{ github.ref_name }} --archive=tar.gz --output ${{ github.ref_name }}.tgz
+          CONTENT=$( sha256sum ${TAR_FILE} )
           SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
           [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
-          printf "%s %s" ${CONTENT} > "${CHECKSUM_FILE}"
+          printf "%s %s" ${CONTENT} > "${TAR_CHECKSUM_FILE}"
+      - name: generate zip checksums
+        run: |
+          CONTENT=$( sha256sum ${ZIP_FILE} )
+          SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
+          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
+          printf "%s %s" ${CONTENT} > "${ZIP_CHECKSUM_FILE}"
 
       - name: write checksum
         uses: softprops/action-gh-release@v2
